### ISSUE TITLE
Emitter Tip

### ISSUE THREAD

**Issue by jonogunn** [amundsson/ghostbusters#1]
Hi there! I was wondering what the emitter tip is for. I can't put my finger on where on the wand that connects to

**Comment by amundsson** [comment]
Hi! The emitter tip is made to fit inside the GBfans tube (https://www.gbfans.com/shop/pack-parts/clear-acrylic-frosted-gun-tip/) so that is what you see when you look into the barrel. I printed it in clear resin so the light will shine thru. :)

**Comment by amundsson** [comment]
See image 😊 
![Uploading IMG_1442.jpeg…]()

**Comment by amundsson** [comment]
![emitter](https://github.com/amundsson/ghostbusters/assets/151675956/102ac7d0-ab2e-4f97-affc-83ee731996d9)

**Comment by jonogunn** [comment]
ah gotcha. where did you come up with that idea?

**Comment by amundsson** [comment]
Sorry, did forget to answer this, This idea is just something i made up. No souce for it but i thought it would be nice to have something to cap it of with.
