### ISSUE TITLE
Accurization of Front Barrel?

### ISSUE THREAD

**Issue by nomakewan** [amundsson/ghostbusters#2]
Firstly, I cannot thank you enough for making these parts. Already they are in my opinion the best way to fit GBFans parts and custom hat lights and switches into the Hasbro wands, hands down.

That said, if I could nitpick a little bit, I would say that it should be possible to not only make them good replacement parts, but in fact make them more accurate to the original props with a fairly minor modification. While the angle of the "box" next to where the front grip goes has had its angle reduced versus the original Hasbro wands, something I appreciate, it is still technically not the right angle and a little off on shape.

On the props, this part is perfectly perpendicular to the front grip, and is more boxy. I have attached photos of the part in question below.

![Sony_Lobby_Set_1_Picture_88](https://github.com/amundsson/ghostbusters/assets/11485516/5c841849-d9da-46a2-924b-8a174c8c4dae)

![039savagecavephoebepack-small](https://github.com/amundsson/ghostbusters/assets/11485516/d80f0e35-c24a-4fba-b309-e9de47df4728)

![Ghostbusters Afterlife 2021 1080p AMZN WEB-DL DDP5 1 H 264-CMRG mkv_snapshot_00 48 37 521](https://github.com/amundsson/ghostbusters/assets/11485516/b4989006-cf79-416e-9eff-5aa77596a30d)

Would it be possible to modify that block to be closer to how it is on the props? If so, that would be fantastic.

Thank you!

**Comment by amundsson** [comment]
Hi

Glad to hear that you like the parts, thank you 😊
Yes, i remember we had that discussion on facebook. Thanks for your input and I will take a look at it to see if i can correct them 😊

At the same time i will correct the lenght of the parts, the ones i have published is 10mm longer then the original haslab to fit the grip i found when i was modeling the parts.

Från: nomakewan ***@***.***>
Skickat: den 5 juli 2024 22:02
Till: amundsson/ghostbusters ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [amundsson/ghostbusters] Accurization of Front Barrel? (Issue #2)


Firstly, I cannot thank you enough for making these parts. Already they are in my opinion the best way to fit GBFans parts and custom hat lights and switches into the Hasbro wands, hands down.

That said, if I could nitpick a little bit, I would say that it should be possible to not only make them good replacement parts, but in fact make them more accurate to the original props with a fairly minor modification. While the angle of the "box" next to where the front grip goes has had its angle reduced versus the original Hasbro wands, something I appreciate, it is still technically not the right angle and a little off on shape.

On the props, this part is perfectly perpendicular to the front grip, and is more boxy. I have attached photos of the part in question below.

Sony_Lobby_Set_1_Picture_88.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/5c841849-d9da-46a2-924b-8a174c8c4dae>

039savagecavephoebepack-small.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/d80f0e35-c24a-4fba-b309-e9de47df4728>

Ghostbusters.Afterlife.2021.1080p.AMZN.WEB-DL.DDP5.1.H.264-CMRG.mkv_snapshot_00.48.37.521.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/b4989006-cf79-416e-9eff-5aa77596a30d>

Would it be possible to modify that block to be closer to how it is on the props? If so, that would be fantastic.

Thank you!

**Comment by amundsson** [comment]
Hi Again,

Have done some adjustments, what do you think? 😊
Kind regards
Joakim

***@***.***

***@***.***



Från: nomakewan ***@***.***>
Skickat: den 5 juli 2024 22:02
Till: amundsson/ghostbusters ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [amundsson/ghostbusters] Accurization of Front Barrel? (Issue #2)


Firstly, I cannot thank you enough for making these parts. Already they are in my opinion the best way to fit GBFans parts and custom hat lights and switches into the Hasbro wands, hands down.

That said, if I could nitpick a little bit, I would say that it should be possible to not only make them good replacement parts, but in fact make them more accurate to the original props with a fairly minor modification. While the angle of the "box" next to where the front grip goes has had its angle reduced versus the original Hasbro wands, something I appreciate, it is still technically not the right angle and a little off on shape.

On the props, this part is perfectly perpendicular to the front grip, and is more boxy. I have attached photos of the part in question below.

Sony_Lobby_Set_1_Picture_88.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/5c841849-d9da-46a2-924b-8a174c8c4dae>

039savagecavephoebepack-small.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/d80f0e35-c24a-4fba-b309-e9de47df4728>

Ghostbusters.Afterlife.2021.1080p.AMZN.WEB-DL.DDP5.1.H.264-CMRG.mkv_snapshot_00.48.37.521.jpg (view on web)<https://github.com/amundsson/ghostbusters/assets/11485516/b4989006-cf79-416e-9eff-5aa77596a30d>

Would it be possible to modify that block to be closer to how it is on the props? If so, that would be fantastic.

Thank you!

**Comment by nomakewan** [comment]
My apologies, where can the adjustments be viewed? It does not appear they have been pushed to the repository yet?

**Comment by amundsson** [comment]
I attached some images inside the mail, maybe they was removed from the mail.

Have not uploaded it yet.
I can send them to your email instead. Whats your address?

Kind regards
Joakim


7 juli 2024 kl. 17:25 skrev nomakewan ***@***.***>:

﻿

My apologies, where can the adjustments be viewed? It does not appear they have been pushed to the repository yet?

**Comment by nomakewan** [comment]
Ah yes, it would appear they were removed by Github.

My address is nomake `underscore` wan `at` yahoo `dot` co `dot` jp.

**Comment by amundsson** [comment]
Images in email is posted here.

![image](https://github.com/amundsson/ghostbusters/assets/151675956/8b417645-0860-4e09-9171-230079c53c9b)

![image](https://github.com/amundsson/ghostbusters/assets/151675956/63280f29-d628-46f9-9862-6a1bcc448aba)


Will upload new files shortly.
